apiVersion: v2
name: redis-utils
description: Shared Redis utilities and connection management for Trading Platform
type: library
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - redis
  - utilities
  - library
  - trading-platform
home: https://github.com/Nwagbara-Group-LLC/redisutils
maintainers:
  - name: Trading Platform Team
    email: platform@nwagbara-group.com
annotations:
  category: Infrastructure
